### ISSUE TITLE
Import and rasterize IUCN data

### ISSUE THREAD

**Issue by JamesDMSpeed** [JamesDMSpeed/PhyloTroph#4]
We need to import the spatial polygons for Norwegian mammals from IUCN and directly rasterize this to 10km resolution. @damarismm - can you do this please.

**Comment by damarismm** [comment]
I uploaded the RScript (mammalIUCN) and the shapefile for the Norwegian mammals (without Svalbard). The shape file for Svalbard is too big to upload. However, the distribution of mammals on Svalbard and Norway is saved as raster brick in mammalNS.RData. This also includes a map of mammal species richness.

**Comment by JamesDMSpeed** [comment]
Great. I have uploaded reptile data (as a shapefile) and plant species richness and phylogenetic diversity (as rasters). Now we just need the birds :-)

**Comment by damarismm** [comment]
Bird data is up now too.

**Comment by JamesDMSpeed** [comment]
There are obviously many species missing from the bird data. This is not ready yet

**Comment by JamesDMSpeed** [comment]
I have now seleceted the species from the total BOTW data that overlap with Norway. There are 279. Tis data (spatial polygons) is uploaded on box and the birds.R script reads in directly from there. 
@damarismm & @kjerstrs, please check the number of species of mammals, reptiles and amphibians is correct. You can then close this issue.

**Comment by damarismm** [comment]
Reptiles and amphibian numbers are correct. As already mentioned @kjerstrs, the wolverine was missing in the mammals, I updated that now.
