### ISSUE TITLE
Reading data

### ISSUE THREAD

**Issue by kjerstrs** [JamesDMSpeed/PhyloTroph#5]
I have some trouble reading the shapefiles showing the ranges for the amphibians and the reptiles. It worked for the mammals (NorwayNew_), so I wonder if the problem is that there are several shapefiles within the Amphibians and the Reptiles folders? I've tried specifying the dsn and layer in the readOGR-function, and moving the different shapefiles into seperate folders, but without results. 
I'm currently working in the 'testing'-file under the R folder.

**Comment by JamesDMSpeed** [comment]
The pathways for the files need to be read from within the repository directory (i.e. the pathway that you would follow from the GitHub repository page).
e.g. 
repN <- readOGR("Data/Ranges/Reptiles", "NorwayReptiles")
Not from a local C drive.

**Comment by JamesDMSpeed** [comment]
P.S. remember to tag @damarismm as an assignee in issues so she also will get notified that you need some help :-)
